version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: mysql:8.0
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: laravel-nginx
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - laravel-network

volumes:
    db_data:

networks:
    laravel-network:
        driver: bridge
